IF DB_ID('Hastane_Otomasyon') IS NOT NULL

   BEGIN 
       ALTER DATABASE [Hastane_Otomasyon] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
	   USE master
	   DROP DATABASE Hastane_Otomasyon
	END
GO

CREATE DATABASE Hastane_Otomasyon

      ON PRIMARY (
	                NAME = 'Hastane_Otomasyon',
					FILENAME = 'c:\database\Hastane_Otomasyon_db.mdf',
					SIZE = 5MB,
					MAXSIZE = 100MB,
					FILEGROWTH = 5MB
	              )
       LOG ON 
	             (  NAME = 'Hastane_Otomasyon_log',
					FILENAME = 'c:\database\Hastane_Otomasyon_log.ldf',
					SIZE = 2MB,
					MAXSIZE = 50MB,
					FILEGROWTH = 1MB
	              )
     
GO
 USE Hastane_Otomasyon
 CREATE TABLE TBLIL
(
   IL_ID INT IDENTITY(1,1) PRIMARY KEY,
   ISIM VARCHAR(20) NOT NULL
)
 GO
 CREATE TABLE TBLILCE 
 (
   ILCE_ID INT IDENTITY(1,1) PRIMARY KEY,
   ISIM VARCHAR(20) NOT NULL,
   IL_ID INT FOREIGN KEY REFERENCES TBLIL(IL_ID) NOT NULL  
)  
GO 
CREATE TABLE TBLKANGRUBU
(
    KAN_ID INT IDENTITY(1,1) PRIMARY KEY,
    KAN_ISIM VARCHAR(10) NOT NULL,
)

GO 
CREATE TABLE TBLHASTA
(
   TC CHAR(11) CONSTRAINT CHKTC CHECK(TC LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL PRIMARY KEY,
   ISIM VARCHAR(20) NOT NULL,
   SOYISIM VARCHAR(20) NOT NULL,
   TELNO VARCHAR(11)UNIQUE CONSTRAINT CHKTELNO CHECK(TELNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
   KILO FLOAT,
   BOY FLOAT,
   CINSIYET BIT NOT NULL,
   DOGUM_TARIHI DATETIME,
   YAS AS DATEDIFF(yy,DOGUM_TARIHI,GETDATE()),
   KAN_ID INT FOREIGN KEY REFERENCES TBLKANGRUBU(KAN_ID) NOT NULL,
   IL_ID INT FOREIGN KEY REFERENCES TBLIL(IL_ID) NOT NULL,  
   ILCE_ID INT FOREIGN KEY REFERENCES TBLILCE(ILCE_ID) NOT NULL,  
)
GO 
CREATE TABLE TBLALERJI
(
    ALERJIID INT IDENTITY(1,1) PRIMARY KEY,
	ALERJI_ISIM VARCHAR(30) NOT NULL,
)
GO
CREATE TABLE TBLHASTA_ALERJILERI
(
    HASTA_ALERJISIID INT IDENTITY(1,1) PRIMARY KEY,
	ALERJIID INT FOREIGN KEY REFERENCES TBLALERJI(ALERJIID) NOT NULL,
	TC CHAR(11) FOREIGN KEY REFERENCES TBLHASTA(TC) NOT NULL,
)
GO
CREATE TABLE TBLRANDEVU
(
    RANDEVU_ID INT IDENTITY(1,1) PRIMARY KEY,
	HASTA_GELIS_TARIHI DATE NOT NULL, 
	HASTA_GELIS_SAATI TIME NOT NULL,
	RANDEVU_TURU VARCHAR(30),
	TC CHAR(11) FOREIGN KEY REFERENCES TBLHASTA(TC) NOT NULL, 
)
GO 
CREATE TABLE TBLTAHLIL
(
   TAHLIL_ID INT IDENTITY(1,1) PRIMARY KEY,
   TAHLIL_ISIM VARCHAR(30) NOT NULL,
)
GO 
CREATE TABLE TBLTAHLIL_TUR
(
    TAHLIL_TUR_ID INT IDENTITY(1,1) PRIMARY KEY,
    TAHLIL_TUR_ISIM VARCHAR(30) NOT NULL,
	TAHLIL_FIYAT MONEY NOT NULL,
	MIN_DEGER FLOAT NOT NULL,
	MAX_DEGER FLOAT NOT NULL,
	TAHLIL_ID INT FOREIGN KEY REFERENCES TBLTAHLIL(TAHLIL_ID) NOT NULL,
)
GO 
CREATE TABLE TBLRANDEVUNUN_TAHLILI
(
   RANDEVU_TAHLILI_ID INT IDENTITY(1,1) PRIMARY KEY,
   RANDEVU_ID INT FOREIGN KEY REFERENCES TBLRANDEVU(RANDEVU_ID) NOT NULL,
   TAHLIL_ID INT FOREIGN KEY REFERENCES TBLTAHLIL(TAHLIL_ID) NOT NULL,
)
GO
CREATE TABLE TBLRANDEVUNUN_TAHLIL_CESIDI
(
   RANDEVU_TAHLIL_CESIDI_ID INT IDENTITY(1,1) PRIMARY KEY,
   SONUC VARCHAR(30) NOT NULL,
   RANDEVU_ID INT FOREIGN KEY REFERENCES TBLRANDEVU(RANDEVU_ID) NOT NULL,
   TAHLIL_TUR_ID  INT FOREIGN KEY REFERENCES TBLTAHLIL_TUR(TAHLIL_TUR_ID ) NOT NULL,
)
GO 
CREATE TABLE TBLRECETE
(
    RECETE_ID INT IDENTITY(1,1) PRIMARY KEY,
	SON_GECERLILIK_TARIH DATE NOT NULL,
	RECETE_KODU VARCHAR(10) UNIQUE NOT NULL,
	YAZILDIGI_TARIH DATE NOT NULL,
	RANDEVU_ID  INT FOREIGN KEY REFERENCES TBLRANDEVU(RANDEVU_ID ) NOT NULL,
)
GO 
CREATE TABLE TBLPERIYOT
(
  PERIYOT_ID INT IDENTITY(1,1) PRIMARY KEY,
  PERIYOT_ADI VARCHAR(15) NOT NULL,
)
GO 
CREATE TABLE TBLETKEN_MADDE
(
   ETKEN_MADDE_ID INT IDENTITY(1,1) PRIMARY KEY,
   ETKEN_MADDE_ISMI VARCHAR(20),
)
GO 
CREATE TABLE TBLILAC
(
   ILAC_ID INT IDENTITY(1,1) PRIMARY KEY,
   ILAC_ISMI VARCHAR(20) UNIQUE NOT NULL,
   ILAC_FORMU VARCHAR(15)NOT NULL,
   YAN_ETKILERI VARCHAR(100)NOT NULL,
   BARKOD_NO VARCHAR(10)UNIQUE NOT NULL,
   FIYAT MONEY NOT NULL,
   KULLANIM_YASI INT NOT NULL,
   ETKEN_MADDE_ID INT FOREIGN KEY REFERENCES TBLETKEN_MADDE(ETKEN_MADDE_ID) NOT NULL,
)
GO 
CREATE TABLE TBLRECETE_ILAC_PERIYOT
( 
   RECETE_ILAC_PERIYOT_ID INT IDENTITY(1,1) PRIMARY KEY,
   DOZ FLOAT NOT NULL,
   KULLANIM_SIKLIGI INT NOT NULL,
   RECETE_ID INT FOREIGN KEY REFERENCES TBLRECETE(RECETE_ID ) NOT NULL,
   ILAC_ID  INT FOREIGN KEY REFERENCES TBLILAC(ILAC_ID) NOT NULL,
   PERIYOT_ID  INT FOREIGN KEY REFERENCES TBLPERIYOT(PERIYOT_ID) NOT NULL,
)
GO
CREATE TABLE TBLTESHIS
(
   TESHIS_ID INT IDENTITY(1,1) PRIMARY KEY,
   TESHIS_ISMI VARCHAR(20) NOT NULL,
)
GO
CREATE TABLE TBLHASTANE 
(
   HASTANE_ID INT IDENTITY(1,1) PRIMARY KEY,
   HASTANE_ISIM VARCHAR(20) NOT NULL,
   HASTANE_TURU VARCHAR(10) NOT NULL,
   IL_ID INT FOREIGN KEY REFERENCES TBLIL(IL_ID) NOT NULL,    
)
GO
CREATE TABLE TBLPOLIKLINIK
(
  POLIKLINIK_ID INT IDENTITY(1,1) PRIMARY KEY,
  POLIKLINIK_ISIM VARCHAR(20) NOT NULL,
)

GO 
CREATE TABLE TBLHASTANE_POLIKLINIGI
(
  HASTANE_POLIKLINIGI_ID INT IDENTITY(1,1) PRIMARY KEY,
  HASTANE_POLIKLINIGI_ISMI VARCHAR(20) NOT NULL,
  ODA_NO INT,
  KAT_NO INT,
  HASTANE_ID INT FOREIGN KEY REFERENCES TBLHASTANE(HASTANE_ID) NOT NULL,
  POLIKLINIK_ID  INT FOREIGN KEY REFERENCES TBLPOLIKLINIK(POLIKLINIK_ID ) NOT NULL,
  )
  GO
  CREATE TABLE TBLHASTANENIN_POLIKLINIGI
  (
     HASTANENIN_POLIKLINIGI_ID INT IDENTITY(1,1) PRIMARY KEY,
	 HASTANE_ID INT FOREIGN KEY REFERENCES TBLHASTANE(HASTANE_ID) NOT NULL,
     POLIKLINIK_ID  INT FOREIGN KEY REFERENCES TBLPOLIKLINIK(POLIKLINIK_ID ) NOT NULL,
  )

 GO
 CREATE TABLE TBLPERSONEL_TURU
 (   PERSONEL_TURU_ID INT IDENTITY(1,1) PRIMARY KEY,
   PERSONEL_TURU_ISIM VARCHAR(20) NOT NULL,
 )
GO
CREATE TABLE TBLBRANS
(
   BRANS_ID INT IDENTITY(1,1) PRIMARY KEY,
   BRANS_ISIM VARCHAR(20) NOT NULL,
)
GO
CREATE TABLE TBLUNVAN
(
   UNVAN_ID INT IDENTITY(1,1) PRIMARY KEY,
   UNVAN_ISIM VARCHAR(20) NOT NULL,
)
GO 
CREATE TABLE TBLPERSONEL
(
   PERSONEL_ID INT IDENTITY(1,1) PRIMARY KEY,
   TC CHAR(11) UNIQUE CONSTRAINT CHKTC2 CHECK(TC LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')NOT NULL,
   ISIM VARCHAR(20) NOT NULL,
   SOYISIM VARCHAR(20) NOT NULL,
   TELNO VARCHAR(10) UNIQUE CONSTRAINT CHKTELNO2 CHECK(TELNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')NOT NULL,
   CINSIYET BIT NOT NULL,
   ÝSE_BASLANGIC_TARIHI DATE NOT NULL,
   DOGUM_TARIHI DATE NOT NULL,
   IL_ID INT FOREIGN KEY REFERENCES TBLIL(IL_ID) NOT NULL,  
   ILCE_ID INT FOREIGN KEY REFERENCES TBLILCE(ILCE_ID) NOT NULL,  
   HASTANE_ID INT FOREIGN KEY REFERENCES TBLHASTANE(HASTANE_ID) NOT NULL,  
   PERSONEL_TURU_ID INT FOREIGN KEY REFERENCES TBLPERSONEL_TURU(PERSONEL_TURU_ID) NOT NULL,
   UNVAN_ID INT FOREIGN KEY REFERENCES TBLUNVAN(UNVAN_ID) NOT NULL,
   BRANS_ID INT FOREIGN KEY REFERENCES TBLBRANS(BRANS_ID) NOT NULL,
)
GO
CREATE TABLE TBLAMELIYAT
(
   AMELIYAT_ID INT IDENTITY(1,1) PRIMARY KEY,
   AMELIYAT_ISMI VARCHAR(20),
   AMELIYAT_TARIHI DATE,
   AMELIYAT_SAATI TIME,
   TC CHAR(11) FOREIGN KEY REFERENCES TBLHASTA(TC) NOT NULL,
   PERSONEL_ID INT FOREIGN KEY REFERENCES TBLPERSONEL(PERSONEL_ID) NOT NULL,
)
GO 
CREATE TABLE TBLRANDEVU_TESHISI
(
   RANDEVU_TESHISI_ID INT IDENTITY(1,1) PRIMARY KEY,
   RANDEVU_TESHISI_ISMI VARCHAR(20),
   RANDEVU_ID INT FOREIGN KEY REFERENCES TBLRANDEVU(RANDEVU_ID) NOT NULL,
   TESHÝS_ID INT FOREIGN KEY REFERENCES  TBLTESHIS(TESHIS_ID) NOT NULL,
   AMELIYAT_ID INT FOREIGN KEY REFERENCES TBLAMELIYAT(AMELIYAT_ID),
)
GO 
CREATE TABLE TBLCALISMA_TAKVIMI
(
   CALISMA_TAKVIMI_ID INT IDENTITY(1,1) PRIMARY KEY,
   CALISMA_TAKVIMI_TARIHI DATE NOT NULL,
   CALISMA_TAKVIMI_SAATI TIME NOT NULL,
   RANDEVU_ID INT FOREIGN KEY REFERENCES TBLRANDEVU(RANDEVU_ID) NOT NULL,
   PERSONEL_ID INT FOREIGN KEY REFERENCES TBLPERSONEL(PERSONEL_ID) NOT NULL,
   HASTANE_POLIKLINIGI_ID INT FOREIGN KEY REFERENCES TBLHASTANE_POLIKLINIGI(HASTANE_POLIKLINIGI_ID) NOT NULL,
)


